# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('user', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('parent', models.IntegerField(default=0)),
            ],
        ),
    ]
